apiVersion: v1
kind: Service
metadata:
  name: mysql-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: mysql
  ports:
  - port: 3306
    targetPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: mongo
  ports:
  - port: 27017
    targetPort: 27017

--- 

apiVersion: v1
kind: Service
metadata:
  name: auth-service-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    service: auth
  ports:
    - port: 3001
      targetPort: 3001

--- 

apiVersion: v1
kind: Service
metadata:
  name: user-service-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    service: user
  ports:
    - port: 3002
      targetPort: 3002

--- 

apiVersion: v1
kind: Service
metadata:
  name: product-service-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    service: product
  ports:
    - port: 3003
      targetPort: 3003

--- 

apiVersion: v1
kind: Service
metadata:
  name: order-service-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    service: order
  ports:
    - port: 3004
      targetPort: 3004

--- 

apiVersion: v1
kind: Service
metadata:
  name: payment-service-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    service: payment
  ports:
    - port: 3005
      targetPort: 3005

