apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-persistent-volume
spec: 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-persistent-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

  
