apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-serivce 
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths: 
          - path: /api/auth/.*
            pathType: Prefix
            backend:
              service:
                name: auth-service-cluster-ip-service
                port: 
                  number: 3001
          - path: /api/user
            pathType: Prefix
            backend:
              service:
                name: user-service-cluster-ip-service
                port: 
                  number: 3002
          - path: /api/product
            pathType: Prefix
            backend:
              service:
                name: product-service-cluster-ip-service
                port: 
                  number: 3003
          - path: /api/order
            pathType: Prefix
            backend:
              service:
                name: order-service-cluster-ip-service
                port: 
                  number: 3004
          - path: /api/payment
            pathType: Prefix
            backend:
              service:
                name: payment-service-cluster-ip-service
                port: 
                  number: 3005
          

          