apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-depl
spec:
  selector:
    matchLabels:
      service: user
  template:
    metadata:
      labels:
        service: user
    spec:
      containers:
      - name: user-service-pod
        image: kunalznk/microservice:user
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3001
        env:
          - name: DOMAIN
            value: "localhost"
          - name: CLIENT
            value: "http://localhost:3000"
          - name: HTTP_PORT
            value: "3002"
          - name: HTTPS_PORT
            value: "443"
          - name: MONGO_USER
            value: "kunal"
          - name: MONGO_HOST
            value: mongo-cluster-ip-service
          - name: MONGO_PASSWORD
            value: "root%40123"
          - name: MONGO_PORT
            value: "27017"
          - name: DATABASE
            value: "USER"  
          - name: PASS
            value: ""
          - name: USER
            value: ""
          - name: JWT_SECRET_KEY
            value: "dcndsjkvnsvn"  
          - name: KAFKA_BROKER_1
            value: "kafka-1.kafka-svc.default.svc.cluster.local:9092"
