export enum ROLE {
  CUSTOMER = "CUSTOMER",
  SELLER = "SELLER",
  DELIVERY_PARTNER = "DELIVERY_PARTNER"
}

export enum ORDER_STATUS  {
    WAITING_FOR_PAYMENT  = "WAITING_FOR_PAYMENT" , 
    PAYMENT_SUCCESS =  "PAYMENT_SUCCESS", 
    OUT_FOR_DELIVERY =  "OUT_FOR_DELIVERY" , 
    COMPLETE = "COMPLETE",
    CANCEL = "CANCEL",
    RETURN = "COMPLETE",
    PAYMENT_FAILED  = "PAYMENT_FAILED" ,
}

 enum USER_TOPIC  {
    USER_REGISTERED = "USER_REGISTERED",
    USER_UPDATED = "USER_UPDATED",
    USER_DELETED = "USER_DELETED"
 }

 enum PRODUCT_TOPIC  {
    PRODUCT_ADDED = "PRODUCT_ADDED",
    PRODUCT_UPDATED = "PRODUCT_UPDATED",
    PRODUCT_DELETED = "PRODUCT_DELETED"
 }

 enum ORDER_TOPIC  {
    ORDER_ADDED = "ORDER_ADDED",
    ORDER_CACEL = "ORDER_CACEL",
    ORDER_RETURN = "PRODUCT_DELETED",
    ORDER_COMPLETED = "ORDER_COMPLETED"
 }

 enum PAYMENT_TOPIC  {
    PAYMENT_ADDED = "PAYMENT_ADDED",
    PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
    PAYMENT_FAIL = "PAYMENT_FAIL"
 }

 enum DELIVERY_TOPIC  {
    DELIVERY_STARTED = "DELIVERY_STARTED",
    DELIVERY_COURIED_PARTNER = "DELIVERY_COURIED_PARTNER",
    DELIVERY_COMPLETED = "DELIVERY_COMPLETED"
 }
 
 export const kafkaTopics = {
    
    USER_TOPIC,
    PRODUCT_TOPIC,
    ORDER_TOPIC,
    PAYMENT_TOPIC,
    DELIVERY_TOPIC

 }

 export enum kafkaClients {
    
    AUTH_CLIENT =  "AUTH_CLIENT",
    USER_CLIENT = "USER_CLIENT",
    PRODUCT_CLIENT = "PRODUCT_CLIENT",
    ORDER_CLIENT = "ORDER_CLIENT",
    PAYMENT_CLIENT = "PAYMENT_CLIENT",
    DELIVRY_CLIENT = "DELIVRY_CLIENT"
 }